FROM node:14-alpine AS builder

ENV NODE_ENV=production

WORKDIR  /App

COPY package*.json .
COPY tsconfig.node.json .

RUN npm ci 

COPY . .

RUN npm run build 

FROM nginx:1.21.0-alpine as production

ENV NODE_ENV=production

WORKDIR /usr/share/nginx/html

COPY --from=builder /App/build  /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]